name: Build, Analyze, and Deploy ASP.Net Core app to Azure Web App - Invaise-BusinessDomain

on:
  push:
    branches:
      - '**'  # Run on all branches
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./src

      - name: Test with coverage
        run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage"
        working-directory: ./src

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Generate coverage report
        run: reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coverage-report -reporttypes:Cobertura

      - name: SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@master
        with:
          organization: adomaspartikas
          projectKey: AdomasPartikas_Invaise.BusinessDomain
          token: ${{ secrets.SONAR_TOKEN }}

      - name: Publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
        working-directory: ./src

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4FCA156C19EB464D9C41128192C3170B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A99D8AC51A3D4DA980A851C178D3F5FA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_21EC107742C4419596E64BDF36906E3A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Invaise-BusinessDomain'
          slot-name: 'Production'
          package: .
