name: Build, Analyze, and Deploy ASP.Net Core app to Azure Web App - Invaise-BusinessDomain

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
# ──────────────────────────────────────────────
# BUILD + TEST + PACKAGE
# ──────────────────────────────────────────────
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET SDK 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Build API (Release)
      run: dotnet build src/Invaise.BusinessDomain.API.csproj -c Release

    # ── UNIT TESTS + COVERAGE ─────────────────
    - name: Run tests and collect coverage
      run: |
        dotnet test Tests/Invaise.BusinessDomain.Test.Unit/Invaise.BusinessDomain.Test.Unit.csproj \
          --configuration Release \
          --collect:"XPlat Code Coverage" \
          --results-directory ./TestResults \
          --verbosity normal

    - name: Locate coverage file
      id: coverage
      run: |
        COV=$(find ./TestResults -name 'coverage.cobertura.xml' | head -n 1)
        echo "COV_PATH=$COV" >> "$GITHUB_ENV"
        echo "Coverage file found at $COV"

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Generate HTML coverage report
      run: |
        reportgenerator -reports:"$COV_PATH" \
                        -targetdir:coverage-report \
                        -reporttypes:Html

    # ── SONARCLOUD ────────────────────────────
    - name: SonarCloud analysis
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io
        SONAR_SCANNER_OPTS: "-Dsonar.cs.cobertura.reportsPaths=$COV_PATH"
      with:
        projectBaseDir: .

    # ── PUBLISH ───────────────────────────────
    - name: Publish API
      run: dotnet publish src/Invaise.BusinessDomain.API.csproj \
            -c Release \
            -o ./publish

    - name: Upload artefact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: api-publish
        path: ./publish

# ──────────────────────────────────────────────
# DEPLOY (only on master)
# ──────────────────────────────────────────────
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Download build artefact
      uses: actions/download-artifact@v4
      with:
        name: api-publish

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4FCA156C19EB464D9C41128192C3170B }}
        tenant-id:  ${{ secrets.AZUREAPPSERVICE_TENANTID_A99D8AC51A3D4DA980A851C178D3F5FA }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_21EC107742C4419596E64BDF36906E3A }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: Invaise-BusinessDomain
        slot-name: Production
        package: ./api-publish
